# Generated by Django 4.2.4 on 2023-09-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0008_rename_image_auction_imageurl"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auction",
            name="imageurl",
        ),
        migrations.AddField(
            model_name="auction",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
